$(document).ready(function(){
	$("#div1").hide(function(){
		$("#div1").show(1000);
	});
	$("#user_info").hover(function(){
		$("#user_info").animate({
		    height:'45%',
		    width:'45%',
		    left:'2%',
		    top:'2%'
	  });
	},
	function(){
		$("#user_info").animate({
		    height:'40%',
		    width:'40%',
		    left:'5%',
		    top:'5%'
	  });
	});
	$("#user_fankui").hover(function(){
		$("#user_fankui").animate({
		    height:'45%',
		    width:'45%',
		    left:'52%',
		    top:'2%'
	  });
	},
	function(){
		$("#user_fankui").animate({
		    height:'40%',
		    width:'40%',
		    left:'55%',
		    top:'5%'
	  });
	});
	$("#user_fenghao").hover(function(){
		$("#user_fenghao").animate({
		    height:'45%',
		    width:'45%',
		    left:'2%',
		    top:'52%'
	  });
	},
	function(){
		$("#user_fenghao").animate({
		    height:'40%',
		    width:'40%',
		    left:'5%',
		    top:'55%'
	  });
	});
	$("#user_other").hover(function(){
		$("#user_other").animate({
		    height:'45%',
		    width:'45%',
		    left:'52%',
		    top:'52%'
	  });
	},
	function(){
		$("#user_other").animate({
		    height:'40%',
		    width:'40%',
		    left:'55%',
		    top:'55%'
	  });
	});


})