$(document).ready(function(){
	//判断变量
	var data_cente_click=true;
	var news_manage_click=false;
	var inform_manage_click=false;
	var user_manage_click=false;
	var cpccs_work_click=false;

	$("#data_cente").css("background-color","#272821");

	//左边导航栏鼠标悬停
	$("#data_cente").hover(function(){
		//鼠标移入事件
		$("#data_cente").css("background-color","#272821");
	},
	function(){
		if(!data_cente_click){
			//鼠标移出事件
			$("#data_cente").css("background-color","#515869");
		}
	});
	$("#news_manage").hover(function(){
		$("#news_manage").css("background-color","#272821");
	},
	function(){
		if(!news_manage_click){
			$("#news_manage").css("background-color","#515869");
		}
	});
	$("#inform_manage").hover(function(){
		$("#inform_manage").css("background-color","#272821");
	},
	function(){
		if(!inform_manage_click){
			$("#inform_manage").css("background-color","#515869");
		}
	});
	$("#user_manage").hover(function(){
		$("#user_manage").css("background-color","#272821");
	},
	function(){
		if(!user_manage_click){
			$("#user_manage").css("background-color","#515869");
		}
	});
	$("#cpccs_work").hover(function(){
		$("#cpccs_work").css("background-color","#272821");
	},
	function(){
		if(!cpccs_work_click){
			$("#cpccs_work").css("background-color","#515869");
		}
	});

	//左边导航栏鼠标点击事件
	$("#data_cente").click(function(){
		//设置css
		$("#data_cente").css("background-color","#272821");
		$("#news_manage").css("background-color","#515869");
		$("#inform_manage").css("background-color","#515869");
		$("#user_manage").css("background-color","#515869");
		$("#cpccs_work").css("background-color","#515869");
		//设置是否被点击标记
		data_cente_click=true;
		news_manage_click=false;
		inform_manage_click=false;
		user_manage_click=false;
		cpccs_work_click=false;
		$("#right").hide(500,function(){
			$("#iframe").attr("src","https://www.baidu.com/");
			$("#right").show(1000);
		});
	});
	$("#news_manage").click(function(){
		$("#data_cente").css("background-color","#515869");
		$("#news_manage").css("background-color","#272821");
		$("#inform_manage").css("background-color","#515869");
		$("#user_manage").css("background-color","#515869");
		$("#cpccs_work").css("background-color","#515869");
		data_cente_click=false;
		news_manage_click=true;
		inform_manage_click=false;
		user_manage_click=false;
		cpccs_work_click=false;
		$("#right").hide(500,function(){
			$("#iframe").attr("src","https://www.so.com/");
			$("#right").show(1000);
		});
	});
	$("#inform_manage").click(function(){
		$("#data_cente").css("background-color","#515869");
		$("#news_manage").css("background-color","#515869");
		$("#inform_manage").css("background-color","#272821");
		$("#user_manage").css("background-color","#515869");
		$("#cpccs_work").css("background-color","#515869");
		data_cente_click=false;
		news_manage_click=false;
		inform_manage_click=true;
		user_manage_click=false;
		cpccs_work_click=false;
		$("#right").hide(500,function(){
			$("#iframe").attr("src","http://www.chinaso.com/");
			$("#right").show(1000);
		});	
	});
	$("#user_manage").click(function(){
		$("#data_cente").css("background-color","#515869");
		$("#news_manage").css("background-color","#515869");
		$("#inform_manage").css("background-color","#515869");
		$("#user_manage").css("background-color","#272821");
		$("#cpccs_work").css("background-color","#515869");
		data_cente_click=false;
		news_manage_click=false;
		inform_manage_click=false;
		user_manage_click=true;
		cpccs_work_click=false;
		$("#right").hide(500,function(){
			$("#iframe").attr("src","https://www.sogou.com/");
			$("#right").show(1000);
		});		
	});
	$("#cpccs_work").click(function(){
		$("#data_cente").css("background-color","#515869");
		$("#news_manage").css("background-color","#515869");
		$("#inform_manage").css("background-color","#515869");
		$("#user_manage").css("background-color","#515869");
		$("#cpccs_work").css("background-color","#272821");
		data_cente_click=false;
		news_manage_click=false;
		inform_manage_click=false;
		user_manage_click=false;
		cpccs_work_click=true;
		$("#right").hide(500,function(){
			$("#iframe").attr("src","https://pinyin.sogou.com/");
			$("#right").show(1000);
		});		
	});

})