$(document).ready(function(){
	$("#div1").hide(function(){
		$("#div1").show(1000);
	});
	$("#add_inform").hover(function(){
		$("#add_inform").animate({
		    height:'45%',
		    width:'45%',
		    left:'2%',
		    top:'2%'
	  });
	},
	function(){
		$("#add_inform").animate({
		    height:'40%',
		    width:'40%',
		    left:'5%',
		    top:'5%'
	  });
	});
	$("#edit_inform").hover(function(){
		$("#edit_inform").animate({
		    height:'45%',
		    width:'45%',
		    left:'52%',
		    top:'2%'
	  });
	},
	function(){
		$("#edit_inform").animate({
		    height:'40%',
		    width:'40%',
		    left:'55%',
		    top:'5%'
	  });
	});
	$("#delete_inform").hover(function(){
		$("#delete_inform").animate({
		    height:'45%',
		    width:'45%',
		    left:'2%',
		    top:'52%'
	  });
	},
	function(){
		$("#delete_inform").animate({
		    height:'40%',
		    width:'40%',
		    left:'5%',
		    top:'55%'
	  });
	});
	$("#see_inform").hover(function(){
		$("#see_inform").animate({
		    height:'45%',
		    width:'45%',
		    left:'52%',
		    top:'52%'
	  });
	},
	function(){
		$("#see_inform").animate({
		    height:'40%',
		    width:'40%',
		    left:'55%',
		    top:'55%'
	  });
	});


})